# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SefaPc\Desktop\btkPythonL\21_PyQt5\check_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(632, 406)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTakeHobbies = QtWidgets.QPushButton(self.centralwidget)
        self.btnTakeHobbies.setGeometry(QtCore.QRect(60, 240, 201, 51))
        self.btnTakeHobbies.setObjectName("btnTakeHobbies")
        self.lblResultHobbies = QtWidgets.QLabel(self.centralwidget)
        self.lblResultHobbies.setGeometry(QtCore.QRect(60, 300, 201, 61))
        self.lblResultHobbies.setText("")
        self.lblResultHobbies.setObjectName("lblResultHobbies")
        self.groupHobbies = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobbies.setGeometry(QtCore.QRect(30, 10, 251, 211))
        self.groupHobbies.setObjectName("groupHobbies")
        self.widget = QtWidgets.QWidget(self.groupHobbies)
        self.widget.setGeometry(QtCore.QRect(20, 30, 201, 161))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbCinema = QtWidgets.QCheckBox(self.widget)
        self.cbCinema.setObjectName("cbCinema")
        self.verticalLayout.addWidget(self.cbCinema)
        self.cbRead = QtWidgets.QCheckBox(self.widget)
        self.cbRead.setObjectName("cbRead")
        self.verticalLayout.addWidget(self.cbRead)
        self.cbSport = QtWidgets.QCheckBox(self.widget)
        self.cbSport.setObjectName("cbSport")
        self.verticalLayout.addWidget(self.cbSport)
        self.groupLesson = QtWidgets.QGroupBox(self.centralwidget)
        self.groupLesson.setGeometry(QtCore.QRect(300, 10, 251, 211))
        self.groupLesson.setObjectName("groupLesson")
        self.layoutWidget = QtWidgets.QWidget(self.groupLesson)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 201, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbWeb = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbWeb.setObjectName("cbWeb")
        self.verticalLayout_3.addWidget(self.cbWeb)
        self.cbProg = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbProg.setObjectName("cbProg")
        self.verticalLayout_3.addWidget(self.cbProg)
        self.cbMath = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbMath.setObjectName("cbMath")
        self.verticalLayout_3.addWidget(self.cbMath)
        self.btnTakeLessons = QtWidgets.QPushButton(self.centralwidget)
        self.btnTakeLessons.setGeometry(QtCore.QRect(330, 240, 201, 51))
        self.btnTakeLessons.setObjectName("btnTakeLessons")
        self.lblResultLessons = QtWidgets.QLabel(self.centralwidget)
        self.lblResultLessons.setGeometry(QtCore.QRect(330, 300, 201, 61))
        self.lblResultLessons.setText("")
        self.lblResultLessons.setObjectName("lblResultLessons")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 632, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTakeHobbies.setText(_translate("MainWindow", "Take checkeds"))
        self.groupHobbies.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbCinema.setText(_translate("MainWindow", "Cinema"))
        self.cbRead.setText(_translate("MainWindow", "Reading Book"))
        self.cbSport.setText(_translate("MainWindow", "Sport"))
        self.groupLesson.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbWeb.setText(_translate("MainWindow", "Web Design"))
        self.cbProg.setText(_translate("MainWindow", "Programming"))
        self.cbMath.setText(_translate("MainWindow", "Mathematics"))
        self.btnTakeLessons.setText(_translate("MainWindow", "Take checkeds"))
