# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SefaPc\Desktop\btkPythonL\21_PyQt5\combo_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 265)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbCities = QtWidgets.QComboBox(self.centralwidget)
        self.cbCities.setGeometry(QtCore.QRect(30, 20, 211, 61))
        self.cbCities.setObjectName("cbCities")
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(260, 20, 171, 61))
        self.lblResult.setObjectName("lblResult")
        self.btnGet = QtWidgets.QPushButton(self.centralwidget)
        self.btnGet.setGeometry(QtCore.QRect(30, 90, 211, 23))
        self.btnGet.setObjectName("btnGet")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(260, 90, 211, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(30, 130, 211, 23))
        self.btnClear.setObjectName("btnClear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 579, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblResult.setText(_translate("MainWindow", "TextLabel"))
        self.btnGet.setText(_translate("MainWindow", "Get Item"))
        self.btnLoad.setText(_translate("MainWindow", "Load Items"))
        self.btnClear.setText(_translate("MainWindow", "Clear Items"))
