# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SefaPc\Desktop\btkPythonL\21_PyQt5\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_MainWindow(object):
    def setupUi(self, UI_MainWindow):
        UI_MainWindow.setObjectName("UI_MainWindow")
        UI_MainWindow.resize(522, 190)
        self.centralwidget = QtWidgets.QWidget(UI_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 51, 21))
        self.label_2.setObjectName("label_2")
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(110, 30, 131, 41))
        self.txt_num1.setObjectName("txt_num1")
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(110, 100, 131, 41))
        self.txt_num2.setObjectName("txt_num2")
        self.btnSum = QtWidgets.QPushButton(self.centralwidget)
        self.btnSum.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.btnSum.setObjectName("btnSum")
        self.btnMinus = QtWidgets.QPushButton(self.centralwidget)
        self.btnMinus.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.btnMinus.setObjectName("btnMinus")
        self.btnMult = QtWidgets.QPushButton(self.centralwidget)
        self.btnMult.setGeometry(QtCore.QRect(260, 90, 75, 23))
        self.btnMult.setObjectName("btnMult")
        self.btnDiv = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiv.setGeometry(QtCore.QRect(260, 120, 75, 23))
        self.btnDiv.setObjectName("btnDiv")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(370, 60, 191, 51))
        self.lbl_result.setObjectName("lbl_result")
        UI_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 522, 21))
        self.menubar.setObjectName("menubar")
        UI_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_MainWindow)
        self.statusbar.setObjectName("statusbar")
        UI_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UI_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(UI_MainWindow)

    def retranslateUi(self, UI_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        UI_MainWindow.setWindowTitle(_translate("UI_MainWindow", "MainWindow"))
        self.label.setText(_translate("UI_MainWindow", "Number 1:"))
        self.label_2.setText(_translate("UI_MainWindow", "Number 2:"))
        self.btnSum.setText(_translate("UI_MainWindow", "+"))
        self.btnMinus.setText(_translate("UI_MainWindow", "-"))
        self.btnMult.setText(_translate("UI_MainWindow", "*"))
        self.btnDiv.setText(_translate("UI_MainWindow", "/"))
        self.lbl_result.setText(_translate("UI_MainWindow", "Answer = "))
